import mongoose from 'mongoose';
import Applicant from '../models/Applicant';
import Job from '../models/Job';
import * as dotenv from "dotenv";

dotenv.config();

const candidates = [
  {
    firstName: 'Sarah',
    lastName: 'Mwangi',
    email: 'sarah.mwangi@email.com',
    phone: '+254-712-345-678',
    skills: [
      { name: 'React', level: 'Advanced' as const, yearsOfExperience: 5 },
      { name: 'TypeScript', level: 'Advanced' as const, yearsOfExperience: 4 },
      { name: 'Node.js', level: 'Expert' as const, yearsOfExperience: 6 },
      { name: 'MongoDB', level: 'Advanced' as const, yearsOfExperience: 4 },
      { name: 'AWS', level: 'Intermediate' as const, yearsOfExperience: 3 },
    ],
    experience: [
      {
        company: 'M-Pesa Tech',
        role: 'Senior Full-Stack Developer',
        startDate: '2018-06',
        endDate: undefined,
        isCurrent: true,
        description: 'Led migration from monolith to microservices architecture',
        technologies: ['React', 'Node.js', 'TypeScript', 'MongoDB', 'AWS'],
      },
    ],
    education: [
      {
        institution: 'University of Nairobi',
        degree: 'BSc Computer Science',
        fieldOfStudy: 'Computer Science',
        startYear: 2014,
        endYear: 2018,
      },
    ],
    projects: [
      {
        name: 'E-Commerce Microservices Platform',
        description: 'Scalable e-commerce platform using microservices architecture',
        role: 'Lead Developer',
        technologies: ['Node.js', 'React', 'MongoDB', 'AWS', 'Docker'],
        link: 'https://sarahmwangi.dev/projects/ecommerce',
        startDate: '2021-01',
        endDate: undefined,
      },
    ],
    availability: {
      status: 'Open to Opportunities',
      type: 'Full-time',
      startDate: '2024-01',
    },
    bio: 'Passionate about scalable web applications and microservices architecture.',
    languages: [
      { name: 'English', proficiency: 'Native' as const },
      { name: 'Swahili', proficiency: 'Native' as const },
    ],
    certifications: [
      { name: 'AWS Certified Solutions Architect', issuer: 'Amazon Web Services', issueDate: '2022-03' },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/sarahmwangi',
      github: 'https://github.com/sarahmwangi',
    },
    portfolioUrl: 'https://sarahmwangi.dev',
    resumeText: 'Experienced full-stack developer with expertise in React and Node.js...',
    source: 'umurava' as const,
  },
  {
    name: 'Kofi Asante',
    email: 'k.asante@email.com',
    phone: '+233-24-123-4567',
    skills: ['Python', 'Django', 'PostgreSQL', 'Docker', 'GraphQL'],
    yearsOfExperience: 5,
    education: { degree: 'BSc Software Engineering', institution: 'KNUST', graduationYear: 2019 },
    currentRole: 'Backend Engineer',
    currentCompany: 'FarmTech Ghana',
    bio: 'Focused on building robust backend systems and data pipelines.',
    portfolioUrl: 'https://kofiasante.dev',
    resumeText: '5 years experience in Python and Django...',
    source: 'umurava' as const,
    jobId: new mongoose.Types.ObjectId(),
  },
  {
    name: 'Amina Diallo',
    email: 'a.diallo@email.com',
    phone: '+221-77-888-9900',
    skills: ['Vue.js', 'JavaScript', 'CSS', 'Firebase', 'UI/UX'],
    yearsOfExperience: 3,
    education: { degree: 'BSc Information Systems', institution: 'Cheikh Anta Diop University', graduationYear: 2021 },
    currentRole: 'Frontend Developer',
    currentCompany: 'SenegalEats',
    bio: 'Creative frontend developer with strong design sense and user experience focus.',
    portfolioUrl: 'https://aminadiallo.dev',
    resumeText: 'Frontend specialist with Vue.js expertise...',
    source: 'external' as const,
    jobId: new mongoose.Types.ObjectId(),
  },
  {
    name: 'David Chen',
    email: 'd.chen@email.com',
    phone: '+86-138-0013-8000',
    skills: ['React', 'Next.js', 'TypeScript', 'Tailwind', 'Figma'],
    yearsOfExperience: 8,
    education: { degree: 'MSc Software Engineering', institution: 'Tsinghua University', graduationYear: 2016 },
    currentRole: 'Tech Lead',
    currentCompany: 'Alibaba Cloud',
    bio: 'Technical leader with extensive experience in distributed systems and team leadership.',
    portfolioUrl: 'https://davidchen.dev',
    resumeText: '8+ years leading frontend teams...',
    source: 'umurava' as const,
    jobId: new mongoose.Types.ObjectId(),
  },
  {
    name: 'Priya Sharma',
    email: 'p.sharma@email.com',
    phone: '+91-98765-43210',
    skills: ['React', 'Node.js', 'PostgreSQL', 'Redis', 'GraphQL'],
    yearsOfExperience: 7,
    education: { degree: 'B.Tech Computer Science', institution: 'IIT Bombay', graduationYear: 2017 },
    currentRole: 'Senior Software Engineer',
    currentCompany: 'Flipkart',
    bio: 'Full-stack engineer passionate about performance optimization and clean code.',
    portfolioUrl: 'https://priyasharma.dev',
    resumeText: 'Performance-focused engineer...',
    source: 'external' as const,
    jobId: new mongoose.Types.ObjectId(),
  },
  {
    name: 'James Wilson',
    email: 'j.wilson@email.com',
    phone: '+44-7700-900123',
    skills: ['Python', 'Machine Learning', 'TensorFlow', 'AWS', 'Kubernetes'],
    yearsOfExperience: 9,
    education: { degree: 'MSc AI', institution: 'Imperial College London', graduationYear: 2015 },
    currentRole: 'Senior ML Engineer',
    currentCompany: 'DeepMind',
    bio: 'AI specialist with focus on NLP and recommendation systems.',
    portfolioUrl: 'https://jameswilson.ai',
    resumeText: 'AI and ML expert...',
    source: 'umurava' as const,
    jobId: new mongoose.Types.ObjectId(),
  },
  {
    name: "Eto'o Samuel",
    email: 'e.samuel@email.com',
    phone: '+237-677-123-456',
    skills: ['JavaScript', 'React', 'MongoDB', 'Express', 'AWS'],
    yearsOfExperience: 4,
    education: { degree: 'BSc Computer Science', institution: 'University of Yaoundé', graduationYear: 2020 },
    currentRole: 'Full-Stack Developer',
    currentCompany: 'CameroonTech',
    bio: 'Versatile developer building solutions for African markets.',
    portfolioUrl: 'https://etosamuel.dev',
    resumeText: 'Full-stack JS developer...',
    source: 'external' as const,
    jobId: new mongoose.Types.ObjectId(),
  },
  {
    name: 'Nadia Benali',
    email: 'n.benali@email.com',
    phone: '+212-612-345-678',
    skills: ['React', 'TypeScript', 'Next.js', 'Prisma', 'PostgreSQL'],
    yearsOfExperience: 5,
    education: { degree: 'MSc Software Engineering', institution: 'ENSIAS', graduationYear: 2019 },
    currentRole: 'Senior Frontend Developer',
    currentCompany: 'Attijariwafa Bank',
    bio: 'TypeScript enthusiast building modern web applications.',
    portfolioUrl: 'https://nadiabenali.dev',
    resumeText: 'TypeScript and React expert...',
    source: 'umurava' as const,
    jobId: new mongoose.Types.ObjectId(),
  },
  {
    name: 'Lebo Mokoena',
    email: 'l.mokoena@email.com',
    phone: '+27-82-123-4567',
    skills: ['Vue.js', 'Nuxt', 'Node.js', 'MongoDB', 'AWS'],
    yearsOfExperience: 6,
    education: { degree: 'BSc Computer Science', institution: 'UCT', graduationYear: 2018 },
    currentRole: 'Senior Developer',
    currentCompany: 'Takealot',
    bio: 'Passionate about e-commerce and scalable solutions.',
    portfolioUrl: 'https://lebo.dev',
    resumeText: 'E-commerce specialist...',
    source: 'external' as const,
    jobId: new mongoose.Types.ObjectId(),
  },
  {
    name: 'Yuki Tanaka',
    email: 'y.tanaka@email.com',
    phone: '+81-90-1234-5678',
    skills: ['React', 'Next.js', 'TypeScript', 'GraphQL', 'AWS'],
    yearsOfExperience: 7,
    education: { degree: 'M.Info', institution: 'University of Tokyo', graduationYear: 2017 },
    currentRole: 'Senior Engineer',
    currentCompany: 'Mercari',
    bio: 'Building scalable marketplace solutions.',
    portfolioUrl: 'https://yukitanaka.dev',
    resumeText: 'Marketplace and e-commerce experience...',
    source: 'umurava' as const,
    jobId: new mongoose.Types.ObjectId(),
  },
  {
    name: 'Carlos Silva',
    email: 'c.silva@email.com',
    phone: '+55-11-98765-4321',
    skills: ['React Native', 'JavaScript', 'Node.js', 'MongoDB', 'Firebase'],
    yearsOfExperience: 5,
    education: { degree: 'BSc Computer Science', institution: 'USP', graduationYear: 2019 },
    currentRole: 'Mobile Developer',
    currentCompany: 'Nubank',
    bio: 'Cross-platform mobile developer building fintech apps.',
    portfolioUrl: 'https://carlossilva.dev',
    resumeText: 'React Native specialist...',
    source: 'external' as const,
    jobId: new mongoose.Types.ObjectId(),
  },
  {
    name: 'Fatima Zahra',
    email: 'f.zahra@email.com',
    phone: '+212-661-234-567',
    skills: ['Python', 'Django', 'PostgreSQL', 'Docker', 'CI/CD'],
    yearsOfExperience: 4,
    education: { degree: 'BSc Software Engineering', institution: 'ENSIAS', graduationYear: 2020 },
    currentRole: 'Backend Developer',
    currentCompany: 'Maroc Telecom',
    bio: 'Backend specialist with DevOps interests.',
    portfolioUrl: 'https://fatimazahra.dev',
    resumeText: 'Backend and DevOps...',
    source: 'umurava' as const,
    jobId: new mongoose.Types.ObjectId(),
  },
  {
    name: 'Thomas Mueller',
    email: 't.mueller@email.com',
    phone: '+49-151-12345678',
    skills: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'Microservices'],
    yearsOfExperience: 10,
    education: { degree: 'Diplom Informatik', institution: 'TU Munich', graduationYear: 2014 },
    currentRole: 'Principal Engineer',
    currentCompany: 'SAP',
    bio: 'Architect with deep expertise in enterprise systems.',
    portfolioUrl: 'https://thomasmueller.dev',
    resumeText: 'Enterprise architecture experience...',
    source: 'external' as const,
    jobId: new mongoose.Types.ObjectId(),
  },
  {
    name: 'Wang Wei',
    email: 'w.wei@email.com',
    phone: '+86-139-0013-8001',
    skills: ['React', 'Vue.js', 'JavaScript', 'HTML/CSS', 'Figma'],
    yearsOfExperience: 3,
    education: { degree: 'BDes Interaction Design', institution: 'Tsinghua University', graduationYear: 2021 },
    currentRole: 'Frontend Developer',
    currentCompany: 'ByteDance',
    bio: 'Design-minded frontend developer bridging UX and code.',
    portfolioUrl: 'https://wangwei.dev',
    resumeText: 'UI-focused developer...',
    source: 'umurava' as const,
    jobId: new mongoose.Types.ObjectId(),
  },
  {
    name: 'Ahmad Hassan',
    email: 'a.hassan@email.com',
    phone: '+20-102-123-4567',
    skills: ['Python', 'Flask', 'PostgreSQL', 'Redis', 'AWS'],
    yearsOfExperience: 6,
    education: { degree: 'BSc Computer Science', institution: 'Cairo University', graduationYear: 2018 },
    currentRole: 'Senior Backend Developer',
    currentCompany: 'Fawry',
    bio: 'API specialist and system architect.',
    portfolioUrl: 'https://ahmadhassan.dev',
    resumeText: 'Backend API experience...',
    source: 'external' as const,
    jobId: new mongoose.Types.ObjectId(),
  },
  {
    name: 'Chloe Martin',
    email: 'c.martin@email.com',
    phone: '+33-6-12-34-56-78',
    skills: ['React', 'Next.js', 'TypeScript', 'Tailwind', 'Storybook'],
    yearsOfExperience: 5,
    education: { degree: 'BSc Engineering', institution: 'EPITA', graduationYear: 2019 },
    currentRole: 'Frontend Developer',
    currentCompany: 'Deezer',
    bio: 'Component library creator and UI engineer.',
    portfolioUrl: 'https://chloemartin.dev',
    resumeText: 'UI component specialist...',
    source: 'umurava' as const,
    jobId: new mongoose.Types.ObjectId(),
  },
  {
    name: 'Raj Patel',
    email: 'r.patel@email.com',
    phone: '+91-98123-45678',
    skills: ['Full-Stack', 'React', 'Node.js', 'MongoDB', 'Serverless'],
    yearsOfExperience: 8,
    education: { degree: 'B.Tech IT', institution: 'IIIT Hyderabad', graduationYear: 2016 },
    currentRole: 'Staff Engineer',
    currentCompany: 'Zomato',
    bio: 'Experienced in building high-traffic platforms.',
    portfolioUrl: 'https://rajpatel.dev',
    resumeText: 'High-scale systems...',
    source: 'external' as const,
    jobId: new mongoose.Types.ObjectId(),
  },
  {
    name: 'Isabella Rossi',
    email: 'i.rossi@email.com',
    phone: '+39-340-123-4567',
    skills: ['React', 'TypeScript', 'Next.js', 'GraphQL', 'Apollo'],
    yearsOfExperience: 6,
    education: { degree: 'Laurea in Informatica', institution: 'Politecnico di Milano', graduationYear: 2018 },
    currentRole: 'Senior Frontend Engineer',
    currentCompany: 'Spotify',
    bio: 'TypeScript and GraphQL enthusiast.',
    portfolioUrl: 'https://isabellarossi.dev',
    resumeText: 'GraphQL and TypeScript expert...',
    source: 'umurava' as const,
    jobId: new mongoose.Types.ObjectId(),
  },
  {
    name: 'Mohammed Al-Farsi',
    email: 'm.alfarsi@email.com',
    phone: '+968-991-234-567',
    skills: ['React', 'Vue.js', 'JavaScript', 'AWS', 'Serverless'],
    yearsOfExperience: 4,
    education: { degree: 'BSc Computer Science', institution: 'Sultan Qaboos University', graduationYear: 2020 },
    currentRole: 'Full-Stack Developer',
    currentCompany: 'Ooredoo Oman',
    bio: 'Building innovative solutions for the MENA region.',
    portfolioUrl: 'https://mohammed.dev',
    resumeText: 'MENA regional experience...',
    source: 'external' as const,
    jobId: new mongoose.Types.ObjectId(),
  },
  {
    name: 'Olivia Thompson',
    email: 'o.thompson@email.com',
    phone: '+1-415-555-0199',
    skills: ['React', 'Next.js', 'TypeScript', 'Prisma', 'PostgreSQL', 'AWS'],
    yearsOfExperience: 9,
    education: { degree: 'BSc Computer Science', institution: 'Stanford University', graduationYear: 2015 },
    currentRole: 'Engineering Manager',
    currentCompany: 'Stripe',
    bio: 'Engineering leader with focus on developer experience and platform engineering.',
    portfolioUrl: 'https://oliviathompson.dev',
    resumeText: 'Leadership and platform engineering...',
    source: 'umurava' as const,
    jobId: new mongoose.Types.ObjectId(),
  },
];

const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI!);
    console.log('MongoDB connected for seeding');

    await Applicant.deleteMany({});
    await Job.deleteMany({});
    console.log('Cleared existing data');

    const job = new Job({
      title: 'Senior Full-Stack Engineer',
      description: 'We are seeking an experienced Full-Stack Engineer to build and scale our recruiting platform. You will work with React, TypeScript, Node.js, and MongoDB to deliver high-quality features.',
      requiredSkills: ['React', 'TypeScript', 'Node.js', 'MongoDB'],
      niceToHaveSkills: ['GraphQL', 'AWS', 'Docker', 'Redis'],
      experienceLevel: 'senior',
      minYearsExperience: 5,
      educationRequirement: "Bachelor's degree in Computer Science or related field",
      department: 'Engineering',
    });
    await job.save();
    console.log('Created job:', job.title);

    const applicantsWithJobId = candidates.map(candidate => ({
      ...candidate,
      jobId: job._id,
    }));

    await Applicant.insertMany(applicantsWithJobId);
    console.log(`Seeded ${candidates.length} candidates`);

    await mongoose.disconnect();
    console.log('Seeding complete!');
    process.exit(0);
  } catch (error) {
    console.error('Seeding error:', error);
    process.exit(1);
  }
};

seed();
